### ISSUE TITLE
theme toggle does not work

### ISSUE THREAD

**Issue by hendriknielaender** [hendriknielaender/double-trouble#130]
after we merged the transition pr into main, the toggle only works once!

**Comment by flyck** [comment]
Temporarily fixed with this:

https://github.com/hendriknielaender/double-trouble/commit/9b821134aaa82e34204c7604fa78b1193a492748

Essentially the header breaks after navigating around with the transitions. On mobile where we have the hamburger menu, that also becomes unresponsive after the first transition.

**Comment by flyck** [comment]
I'll guess I'll close the issue as its fixed.

Created a new issue #188 to re-enable the transitions
