### ISSUE TITLE
Add redirect for https://double-trouble.dev/ to the www domain

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#4]
Seems like go-daddy doesnt support non-www, so the redirect will also do

**Comment by hendriknielaender** [comment]
https://docs.github.com/de/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain-and-the-www-subdomain-variant

switched to non-www instead of www. See https://github.com/hendriknielaender/double-trouble/commit/4b9c6e170a0b00bc4d7f6be823069a1c92a2fcc1

**Comment by flyck** [comment]
https://stackoverflow.com/questions/54817253/github-pages-https-www-redirect this solved it!!!
